src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CarRepository::class)
 */
class Car
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $model;

    /**
     * @ORM\Column(type="integer")
     */
    private $production_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $capacity;

    /**
     * @ORM\Column(type="integer")
     */
    private $mileage;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $vin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $registration_number;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $client;

    /**
     * @ORM\OneToMany(targetEntity=Order::class, mappedBy="car")
     */
    private $orders;

    public function __construct()
    {
        $this->orders = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getProductionDate(): ?int
    {
        return $this->production_date;
    }

    public function setProductionDate(int $production_date): self
    {
        $this->production_date = $production_date;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

    public function getMileage(): ?int
    {
        return $this->mileage;
    }

    public function setMileage(int $mileage): self
    {
        $this->mileage = $mileage;

        return $this;
    }

    public function getVin(): ?string
    {
        return $this->vin;
    }

    public function setVin(string $vin): self
    {
        $this->vin = $vin;

        return $this;
    }

    public function getRegistrationNumber(): ?string
    {
        return $this->registration_number;
    }

    public function setRegistrationNumber(string $registration_number): self
    {
        $this->registration_number = $registration_number;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->setCar($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            // set the owning side to null (unless already changed)
            if ($order->getCar() === $this) {
                $order->setCar(null);
            }
        }

        return $this;
    }
}

src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Car::class, inversedBy="orders")
     * @ORM\JoinColumn(nullable=false)
     */
    private $car;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isArchive;

    /**
     * @ORM\OneToMany(targetEntity=MadeService::class, mappedBy="orders")
     */
    private $madeServices;

    /**
     * @ORM\OneToMany(targetEntity=Invoice::class, mappedBy="orders")
     */
    private $invoices;

    public function __construct()
    {
        $this->madeServices = new ArrayCollection();
        $this->invoices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCar(): ?Car
    {
        return $this->car;
    }

    public function setCar(?Car $car): self
    {
        $this->car = $car;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getIsArchive(): ?bool
    {
        return $this->isArchive;
    }

    public function setIsArchive(bool $isArchive): self
    {
        $this->isArchive = $isArchive;

        return $this;
    }

    /**
     * @return Collection|MadeService[]
     */
    public function getMadeServices(): Collection
    {
        return $this->madeServices;
    }

    public function addMadeService(MadeService $madeService): self
    {
        if (!$this->madeServices->contains($madeService)) {
            $this->madeServices[] = $madeService;
            $madeService->setOrders($this);
        }

        return $this;
    }

    public function removeMadeService(MadeService $madeService): self
    {
        if ($this->madeServices->removeElement($madeService)) {
            // set the owning side to null (unless already changed)
            if ($madeService->getOrders() === $this) {
                $madeService->setOrders(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Invoice[]
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): self
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices[] = $invoice;
            $invoice->setOrders($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): self
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getOrders() === $this) {
                $invoice->setOrders(null);
            }
        }

        return $this;
    }
}

src/Controller/OrdersController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Entity\MadeService;
use App\Entity\Order;
use App\Entity\Service;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class OrdersController extends AbstractController
{

    /**
     * @Route("/orders", name="orders")
     */
    public function showAllOrders()
    {
        $orders = $this->getDoctrine()->getRepository(Order::class)->findAll();
        $html = $this->renderView('orders/index.html.twig', ['orders' => $orders]);

        return new Response($html);
    }

    /**
     * @Route("/orders/view/{id}", name="view_order")
     */
    public function viewOrder(Request $request, $id)
    {
        $order = $this->getDoctrine()->getRepository(Order::class)->find($id);
        $order->setStatus($order->getStatus());

        $form = $this->createFormBuilder($order)
            ->add('status', ChoiceType::class, [
                'label' => false,
                'attr' => ['class' => 'form-control chosen'],
                'choices' => [
                        'Oczekujące' => '1',
                        'Diagnozowanie' => '2',
                        'Naprawa' => '3',
                        'Zakończone' => '4',
                    ]])
            ->add('save', SubmitType::class, array('label' => 'Zmień', 'attr' => array('class' => 'btn btn-primary btn-lg btn-block')))
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $status = $form['status']->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $order = $entityManager->getRepository(Order::class)->find($id);
            $order->setStatus($status);
            $entityManager->flush();
            $this->addFlash("changeOrderStatus", "Status zlecenia został zmieniony!");

            return $this->redirectToRoute('orders');
        }

        $html = $this->renderView('orders/view.html.twig', [
            'order' => $order,
            'form' => $form->createView()
        ]);

        return new Response($html);
    }

    /**
     * @Route("/orders/add", name="add_order")
     */
    public function addOrder(Request $request)
    {
        $order = new Order();

        $form = $this->createFormBuilder()
            ->add('id', EntityType::class, [
                'class' => Car::class,
                'label' => 'Wybierz numer rejestracyjny pojazdu:',
                'attr' => array('class' => 'form-control chosen'),
                'choice_label' => function (Car $carEntity) {
                    return vsprintf('%s', [
                        $carEntity->getRegistrationNumber(),
                    ]);
                },
            ])
            ->add('comments', TextareaType::class, array('label' => 'Uwagi klienta:', 'attr' => array('class' => 'form-control', 'cols' => '5', 'rows' => '5', 'placeholder' => 'np. Samochód nie odpala.')))
            ->add('save', SubmitType::class, array('label' => 'Dodaj', 'attr' => array('class' => 'btn btn-primary btn-lg btn-block')))
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $car_id = $form['id']->getData();
            $comments = $form['comments']->getData();

            $order->setCar($car_id);
            $order->setComments($comments);
            $order->setStatus(1);
            $order->setIsArchive(0);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($order);
            $entityManager->flush();
            $this->addFlash("addOrder", "Zlecenie zostało dodane!");

            return $this->redirectToRoute('orders');
        }

        $html = $this->renderView('orders/add.html.twig', [
            'form' => $form->createView()
        ]);

        return new Response($html);
    }

    /**
     * @Route("/orders/edit/{id}", name="edit_order")
     */
    public function editOrder(Request $request, $id)
    {
        $order = $this->getDoctrine()->getRepository(Order::class)->find($id);
        $order->setComments($order->getComments());

        $form = $this->createFormBuilder($order)
            ->add('comments', TextareaType::class, array('label' => 'Uwagi klienta:', 'attr' => array('class' => 'form-control', 'cols' => '5', 'rows' => '5')))
            ->add('save', SubmitType::class, array('label' => 'Edytuj', 'attr' => array('class' => 'btn btn-primary btn-lg btn-block')))
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $comments = $form['comments']->getData();

            $entityManager = $this->getDoctrine()->getManager();
            $order = $entityManager->getRepository(Order::class)->find($id);
            $order->setComments($comments);
            $entityManager->flush();
            $this->addFlash("editOrder", "Edycja danych zlecenia została wykonana pomyślnie!");

            return $this->redirectToRoute('orders');
        }

        $html = $this->renderView('orders/edit.html.twig', [
            'form' => $form->createView()
        ]);

        return new Response($html);
    }

    /**
     * @Route("/orders/add-service/{id}", name="add_service_to_order")
     */
    public function addServiceToOrder(Request $request, $id)
    {
        $orderId = $this->getDoctrine()->getRepository(Order::class)->find($id);
        $madeService = new MadeService();

        $form = $this->createFormBuilder()
            ->add('id', EntityType::class, [
                'class' => Service::class,
                'label' => false,
                'attr' => array('class' => 'form-control chosen'),
                'choice_label' => function (Service $serviceEntity) {
                    return vsprintf('%s', [
                        $serviceEntity->getName(),
                    ]);
                },
            ])
            ->add('save', SubmitType::class, array('label' => 'Dodaj', 'attr' => array('class' => 'btn btn-primary btn-lg btn-block')))
            ->getForm();

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid())
        {
            $serviceId = $form['id']->getData();

            $madeService->setService($serviceId);
            $madeService->setOrders($orderId);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($madeService);
            $entityManager->flush();
        }

        $madeServicesByOrder = $this->getDoctrine()->getRepository(MadeService::class)->findBy( array('orders' => $id));

        $html = $this->renderView('orders/add-service.html.twig', [
            'madeServicesByOrder' => $madeServicesByOrder,
            'form' => $form->createView()
            ]);

        return new Response($html);
    }

    /**
     * @Route("/orders/delete-service/{id}", name="delete_service_from_order")
     */
    public function deleteServiceFromOrder($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $madeService = $entityManager->getRepository(MadeService::class)->find($id);
        $entityManager->remove($madeService);
        $entityManager->flush();
        $this->addFlash("deleteServiceFromOrder", "Wybrana usługa została usunięta ze zlecenia!");

        return $this->redirectToRoute('orders');

    }

    /**
     * @Route("/orders/delete/{id}", name="delete_order")
     */
    public function deleteOrder($id)
    {
        $entityManager = $this->getDoctrine()->getManager();
        $order = $entityManager->getRepository(Order::class)->find($id);
        $order->setisArchive(1);
        $entityManager->flush();
        $this->addFlash("deleteOrder", "Zlecenie zostało usunięte!");

        return $this->redirectToRoute('orders');
    }
}

templates/orders/add-service.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dodaj usługę{% endblock %}
{% block body %}
    <div id="header" style="padding-top:20px;">
        <h1 style="text-align:center">Lista wykonanych usług:</h1>
    </div>
    <div class="container">
        {{ form_start(form) }}
        <div class="col">
            <table class="table table-striped table-hover">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Lp.</th>
                    <th scope="col">Nazwa usługi</th>
                    <th scope="col">Cena brutto</th>
                    <th scope="col">Akcja</th>
                </tr>
                </thead>
                    <tbody>
                    {% set positionNumber = 0 %}
                        {% for madeServiceByOrder in madeServicesByOrder %}
                            {% set positionNumber = positionNumber + 1 %}
                        <tr>
                            <td>{{ positionNumber }}.</td>
                            <td>{{ madeServiceByOrder.service.name }}</td>
                            <td>{{ madeServiceByOrder.service.grossPrice}} zł</td>
                            <td>
                                <a href="/orders/delete-service/{{ madeServiceByOrder.id }}" class="btn btn-danger btn-sm">Usuń</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
            </table>
            <div id="col">
                <h1 style="text-align:center; padding-top:20px;">Dodaj wykonaną usługę:</h1>
            </div>
            <div class="form-group">
                <div class="col">
                    {{ form_row(form.id) }}
                    <script type="text/javascript">
                        $(function() {
                            $('.chosen').chosen();
                        });
                    </script>
                </div>
            </div>
            <div class="form-group">
                <div class="col">
                    {{ form_row(form.save) }}
                </div>
            </div>
            {{ form_end(form) }}
        </div>
{% endblock %}

templates/orders/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Dodaj zlecenie{% endblock %}
{% block body %}
    <div id="header" style="padding-top:20px;">
        <h1 style="text-align:center">Dodaj zlecenie:</h1>
    </div>
    <div class="container">
        {{ form_start(form) }}
        <div class="form-group">
            <div class="col">
                {{ form_row(form.id) }}
                <script type="text/javascript">
                    $(function() {
                        $('.chosen').chosen();
                    });
                </script>
            </div>
        </div>
        <div class="form-group">
            <div class="col">
                {{ form_row(form.comments) }}
            </div>
        </div>
        <div class="form-group">
            <div class="col">
                {{ form_row(form.save) }}
            </div>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/orders/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edytuj dane zlecenia{% endblock %}
{% block body %}
    <div id="header" style="padding-top:20px;">
        <h1 style="text-align:center">Edytuj dane zlecenia:</h1>
    </div>
    <div class="container">
        {{ form_start(form) }}
        <div class="form-group">
            <div class="col">
                {{ form_row(form.comments) }}
            </div>
        </div>
        <div class="form-group">
            <div class="col">
                {{ form_row(form.save) }}
            </div>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/orders/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Lista zleceń{% endblock %}
{% block body %}
    <div id="header" style="padding-top:20px;">
        <h1 style="text-align:center">Lista zleceń:</h1>
    </div>
    <div class="container">
        <div class="row">
            {% for message in app.flashes('addOrder') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            {% for message in app.flashes('editOrder') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            {% for message in app.flashes('changeOrderStatus') %}
                <div class="alert alert-success">
                    {{ message }}
                </div>
            {% endfor %}
            {% for message in app.flashes('deleteOrder') %}
                <div class="alert alert-danger">
                    {{ message }}
                </div>
            {% endfor %}
            {% for message in app.flashes('deleteServiceFromOrder') %}
                <div class="alert alert-danger">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
        <div class="row">
            <table class="table table-striped table-hover">
                <thead class="thead-dark">
                <tr>
                    <th scope="col">Lp.</th>
                    <th scope="col">Klient</th>
                    <th scope="col">Numer rejestracyjny</th>
                    <th scope="col">Status zlecenia</th>
                    <th scope="col">Akcja</th>
                </tr>
                </thead>
                    <tbody>
                    {% set positionNumber = 0 %}
                        {% for order in orders %}
                            {% set positionNumber = positionNumber + 1 %}
                        <tr>
                            {% if order.isArchive == 0  %}
                            <th scope="row">{{ positionNumber }}.</th>
                            <td>{{ order.car.client.name }}</td>
                            <td>{{ order.car.registrationNumber }}</td>
                            <td>
                                {% if order.status == 1  %}
                                    <p>Oczekujące</p>
                                {% elseif order.status == 2 %}
                                    <p>Diagnozowanie</p>
                                {% elseif order.status == 3 %}
                                    <p>Naprawa</p>
                                {% else %}
                                    <p>Zakończone</p>
                                {% endif %}
                            </td>
                            <td>
                                <a href="/orders/view/{{order.id}}" class="btn btn-primary btn-sm">Szczegóły zlecenia</a>
                                <a href="/orders/add-service/{{order.id}}" class="btn btn-secondary btn-sm">Dodaj wykonanie usługi</a>
                                <a href="/orders/edit/{{ order.id }}" class="btn btn-success btn-sm">Edytuj zlecenie</a>
                                <a href="/orders/delete/{{ order.id }}" class="btn btn-danger btn-sm">Usuń zlecenie</a>
                            </td>
                        </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
            </table>
        </div>
            <div class="row">
                <a href="/orders/add" class="btn btn-danger btn-lg btn-block">Dodaj zlecenie</a>
            </div>
    </div>
{% endblock %}

templates/orders/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Informacje o zleceniu{% endblock %}
{% block body %}
    <div id="header" style="padding-top:20px;">
        <h1 style="text-align:center">Informacje o zleceniu:</h1>
    </div>
    <div class="container">
        {{ form_start(form) }}
        <div class="form-group">
            <div class="col">
                <fieldset>
                    <label class="control-label" for="orderNumber">Numer zlecenia:</label>
                    <input class="form-control" id="orderNumber" type="text" placeholder="{{ order.id }}" readonly="">
                </fieldset>
            </div>
        </div>
        <div class="form-group">
            <div class="col">
                <fieldset>
                    <label class="control-label" for="clientName">Klient:</label>
                    <input class="form-control" id="clientName" type="text" placeholder="{{ order.car.client.name }}" readonly="">
                </fieldset>
            </div>
        </div>
        <div class="form-group">
            <div class="col">
                <fieldset>
                    <label class="control-label" for="registrationNumber">Samochód:</label>
                    <input class="form-control" id="registrationNumber" type="text" placeholder="{{ order.car.brand }} {{ order.car.model }} ({{ order.car.registrationNumber }})" readonly="">
                </fieldset>
            </div>
        </div>
        <div class="form-group">
            <div class="col">
                <fieldset>
                    <label class="control-label" for="comments">Uwagi klienta:</label>
                    <textarea class="form-control" id="comments" cols="5" rows="5" placeholder="{{ order.comments }}" readonly=""></textarea>
                </fieldset>
            </div>
        </div>
        <div id="orderStatus">
            <h1 style="text-align:center; font-weight:bold">
                {% if order.status == 1  %}
                    Oczekujące
                {% elseif order.status == 2 %}
                    Diagnozowanie
                {% elseif order.status == 3 %}
                    Naprawa
                {% else %}
                    Zakończone
                {% endif %}
            </h1>
            <h1 style="text-align:center; padding-top:20px;">Zmień status zlecenia:</h1>
        </div>
        <div class="form-group">
            <div class="col">
                {{ form_row(form.status) }}
                <script type="text/javascript">
                    $(function() {
                        $('.chosen').chosen();
                    });
                </script>
            </div>
        </div>
        <div class="form-group">
            <div class="col">
                {{ form_row(form.save) }}
            </div>
        </div>
        {{ form_end(form) }}
    </div>
{% endblock %}